image: kaiwinter/docker-java8-maven


before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - chmod +x ./gradlew

cache:
  paths:
    - .gradle/wrapper

stages:
  - all

build:
  stage: all
  script:
    - ./gradlew :resource-compiler:assemble :resource-compiler:test :resource-compiler:shadowJar :resource-compiler:proguard
  artifacts:
    paths:
      - /resource-compiler/build/libs/
    expire_in: 1 week

